version: '3.8'

services:
  mysql:
    image: mysql
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
