version: '3.8'

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
      - MYSQL_USER=tvzcorp
    ports:
      - '3306:3306'

  redis:
    image: redis
    ports:
      - '6379:6379'
