version: '3.8'

services:
  tvzcorp-db:
    image: mysql
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  tvzcorp-backend:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    env_file:
      - .env

volumes:
  mysql-data:
