version: '3.8'

services:
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=tvzcorp
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=password
    ports:
      - '3306:3306'

  redis:
    image: redis
    ports:
      - '6379:6379'
